name: schedule_dbt_run

on:
  #  schedule:
  #   # run at 7AM every single day
  #   # https://crontab.guru <-- for generating CRON expression
  #   - cron: "0 7 * * *"
   push:
    branches:
    # run on push to development branch
    - development
env:
 DBT_PROFILES_DIR: ${{ github.workspace }}
 DBT_SNOWFLAKE_USERNAME: "dbt"
 DBT_SNOWFLAKE_PW: "dbtpassword123"
 DBT_SNOWFLAKE_ROLE: "transform"
jobs:
   schedule_dbt_run:
    name: schedule_dbt_run
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@main
    # - uses: actions/setup-python@v1
    #     with:
    #     python-version: "3.7.x"

      - name: Install dependencies
        run: |
          pip install dbt-snowflake
      - name: Install dbt dependecies
        run: 
          dbt deps
          

    # dbt related commands here - run use --target prod/dev to run for specific environments
      # - name: Run dbt SEEDS
      #   run: dbt seed  
      - name: Run dbt models
        run: dbt run --target dev
        # --project-dir testdbtproj/ --profiles.  # works unexpectedly
      # - name: Test dbt models 
      #   run: dbt test --profiles-dir ./ 